In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import classification_report


In [38]:
df = pd.read_csv("Breast Cancer Data Set.csv")

In [39]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [41]:
df = df.drop(columns = "Unnamed: 32", axis=1)

In [42]:
x = df.iloc[:,3:-1].values
y = df.iloc[:,-1].values

In [43]:
x

array([[1.038e+01, 1.228e+02, 1.001e+03, ..., 7.119e-01, 2.654e-01,
        4.601e-01],
       [1.777e+01, 1.329e+02, 1.326e+03, ..., 2.416e-01, 1.860e-01,
        2.750e-01],
       [2.125e+01, 1.300e+02, 1.203e+03, ..., 4.504e-01, 2.430e-01,
        3.613e-01],
       ...,
       [2.808e+01, 1.083e+02, 8.581e+02, ..., 3.403e-01, 1.418e-01,
        2.218e-01],
       [2.933e+01, 1.401e+02, 1.265e+03, ..., 9.387e-01, 2.650e-01,
        4.087e-01],
       [2.454e+01, 4.792e+01, 1.810e+02, ..., 0.000e+00, 0.000e+00,
        2.871e-01]])

In [44]:
y

array([0.1189 , 0.08902, 0.08758, 0.173  , 0.07678, 0.1244 , 0.08368,
       0.1151 , 0.1072 , 0.2075 , 0.08452, 0.1048 , 0.1023 , 0.06287,
       0.1431 , 0.1341 , 0.08216, 0.1142 , 0.07615, 0.07259, 0.08183,
       0.07773, 0.09946, 0.07526, 0.09564, 0.1059 , 0.1275 , 0.07421,
       0.09876, 0.07919, 0.09782, 0.1402 , 0.08482, 0.1123 , 0.1233 ,
       0.08633, 0.1014 , 0.06169, 0.05504, 0.1071 , 0.07146, 0.09606,
       0.1038 , 0.1027 , 0.09618, 0.09185, 0.07409, 0.1179 , 0.08301,
       0.06917, 0.06563, 0.08025, 0.07408, 0.07987, 0.07873, 0.07036,
       0.08294, 0.1094 , 0.06289, 0.09026, 0.0802 , 0.07712, 0.1132 ,
       0.0849 , 0.1031 , 0.08911, 0.09211, 0.06641, 0.1175 , 0.0641 ,
       0.06589, 0.1084 , 0.1339 , 0.103  , 0.07609, 0.06387, 0.07191,
       0.1108 , 0.09964, 0.07918, 0.08851, 0.1016 , 0.1051 , 0.09203,
       0.07924, 0.08579, 0.06846, 0.09288, 0.09261, 0.08473, 0.07246,
       0.06828, 0.06206, 0.06603, 0.08234, 0.08368, 0.07376, 0.08988,
       0.08756, 0.09

In [45]:
from sklearn .preprocessing import LabelEncoder

le = LabelEncoder()
le2 = LabelEncoder()

x[:,1] = le.fit_transform(x[:,1])
x[:,2] = le.fit_transform(x[:,2])

In [46]:
x

array([[1.038e+01, 4.550e+02, 4.520e+02, ..., 7.119e-01, 2.654e-01,
        4.601e-01],
       [1.777e+01, 4.860e+02, 5.130e+02, ..., 2.416e-01, 1.860e-01,
        2.750e-01],
       [2.125e+01, 4.780e+02, 4.870e+02, ..., 4.504e-01, 2.430e-01,
        3.613e-01],
       ...,
       [2.808e+01, 4.100e+02, 4.210e+02, ..., 3.403e-01, 1.418e-01,
        2.218e-01],
       [2.933e+01, 5.000e+02, 5.010e+02, ..., 9.387e-01, 2.650e-01,
        4.087e-01],
       [2.454e+01, 1.000e+00, 3.000e+00, ..., 0.000e+00, 0.000e+00,
        2.871e-01]])

In [47]:
from sklearn.model_selection import train_test_split

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.3, random_state = 1)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [49]:
from sklearn .preprocessing import StandardScaler

sc = StandardScaler()

xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

In [50]:
# 1.Initilize the ANN Model

model = Sequential()

# 2.Pass hidden layer

model.add(Dense(units = 6, activation = "relu"))

# 3.Pass Activation Funcation

model.add(Dense(units = 1, activation = "sigmoid"))

# 4.To Establish the connection between layers

model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = ["accuracy"])

# 5.Train the model

model.fit(xtrain, ytrain, batch_size = 30, epochs = 100)

# 6.Take Prediction

ypred = model.predict(xtest)

# 7.Set Threshhold Value

ypred = ypred>0.5

# 8.Get classification report

print(classification_report(ytest,ypred))

Epoch 1/100
14/14 [==============================] - 2s 7ms/step - loss: 0.8752 - accuracy: 0.0000e+00
Epoch 2/100
14/14 [==============================] - 0s 8ms/step - loss: 0.7912 - accuracy: 0.0000e+00
Epoch 3/100
14/14 [==============================] - 0s 7ms/step - loss: 0.7158 - accuracy: 0.0000e+00
Epoch 4/100
14/14 [==============================] - 0s 9ms/step - loss: 0.6535 - accuracy: 0.0000e+00
Epoch 5/100
14/14 [==============================] - 0s 12ms/step - loss: 0.5982 - accuracy: 0.0000e+00
Epoch 6/100
14/14 [==============================] - 0s 11ms/step - loss: 0.5502 - accuracy: 0.0000e+00
Epoch 7/100
14/14 [==============================] - 0s 9ms/step - loss: 0.5106 - accuracy: 0.0000e+00
Epoch 8/100
14/14 [==============================] - 0s 9ms/step - loss: 0.4783 - accuracy: 0.0000e+00
Epoch 9/100
14/14 [==============================] - 0s 7ms/step - loss: 0.4530 - accuracy: 0.0000e+00
Epoch 10/100
14/14 [==============================] - 0s 7ms/step - los

14/14 [==============================] - 0s 6ms/step - loss: 0.2969 - accuracy: 0.0000e+00
Epoch 80/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2967 - accuracy: 0.0000e+00
Epoch 81/100
14/14 [==============================] - 0s 8ms/step - loss: 0.2965 - accuracy: 0.0000e+00
Epoch 82/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2963 - accuracy: 0.0000e+00
Epoch 83/100
14/14 [==============================] - 0s 9ms/step - loss: 0.2960 - accuracy: 0.0000e+00
Epoch 84/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2958 - accuracy: 0.0000e+00
Epoch 85/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2956 - accuracy: 0.0000e+00
Epoch 86/100
14/14 [==============================] - 0s 7ms/step - loss: 0.2954 - accuracy: 0.0000e+00
Epoch 87/100
14/14 [==============================] - 0s 6ms/step - loss: 0.2953 - accuracy: 0.0000e+00
Epoch 88/100
14/14 [==============================] - 0s 9ms/step - loss: 0.2

ValueError: Classification metrics can't handle a mix of continuous and binary targets

In [51]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(xtrain, ytrain)

ypred = logreg.predict(xtest)

print(classification_report(ytest, ypred))

ValueError: Unknown label type: 'continuous'